baseURL = "https://drmoron-escape-room-casino.netlify.app/"
languageCode = "en-us"
title = "Lucky Strike Casino Opeartions"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

# Allow raw html
[markup.goldmark.renderer]
  unsafe= true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 0
  [[menu.main]]
    name = "Email"
    url = "/email/"
    weight = 20
  [[menu.main]]
    name = "Shipping"
    url = "/shipping/"
    weight = 60
